### ISSUE TITLE
Repository is outdated

### ISSUE THREAD

**Issue by KubeRoot** [Frenqy/InstancedLoot_continuation#1]
Hello, original author of InstancedLoot here. Somebody who was looking forward to the mod being hopefully updated notified me, and I decided it might be a good idea to take a look and reach out.

First of all, thank you for taking this up - I haven't had the time or motivation to work on my mods, and InstancedLoot in particular needs work. I want to make it clear that I have nothing against somebody making a fork and continuing the mod on their own.

For the actual issue title, I noticed you have this repository linked as the homepage for the mod, but the latest commit seems to be my last commit. I'm guessing you're still figuring things out, but wanted to let you know, and also wanted an excuse just to reach out :P

If you need any information about the code, feel free to ask me questions, we could get in touch on discord or steam chat if it's more convenient for you.

**Comment by Frenqy** [comment]
oh! sorry, i forgot to push my commit

**Comment by KubeRoot** [comment]
Thanks! My offer to get in touch is still open.

I could make separate issues if you'd like, but if you don't mind me pointing a couple things out:

It seems you created a second solution file - the source already had a solution file, in the form of RoR2Mods.sln, which is named as such because I've been reusing a template when making new mods. I'd recommend keeping only one solution file, there's no problem with deleting the original, but it seems confusing as is.

If you're going to continue developing the mod, it might be a good idea to either make your own repository for libraries or un-submodule it, or switch to a different scheme entirely. My repository isn't updated automatically, I just update it when I need to using a script that calls https://github.com/BepInEx/BepInEx.AssemblyPublicizer/ for every assembly. I could try to help get that set up if you'd like, or you could switch to the NuGet package for game libraries and manually pulling in mod dependencies.

I would also recommend you keep the original text in the readme - I'd personally put the fork notice at the top and keep the rest as-is for the moment, since the information inside is still relevant. Either way, I think you really should make a readme for the thunderstore page, since currently the mod page is completely empty.

Ultimately though, this is your mod now, and you can do with it as you wish, those are only my suggestions. I hope you can continue developing it into the mod the community deserves, thank you and good luck!

**Comment by Frenqy** [comment]
Thank you for your guidance!

This is my first time participating in mod development, and there are many things I don't know how to do. 

I will make the modifications as soon as possible

**Comment by 6d657263757279** [comment]
@Frenqy I did not want to open an issue just for this, so I apologize for the non-technical ping here, but I wasn't aware if you were part of the RoR2 modding discord server. I want to thank you for taking up this mod and working with @KubeRoot to update it. This mod makes the game much more enjoyable to play with my friends and s/o. Please feel encouraged and welcome to Risk of Rain 2 modding!

**Comment by KubeRoot** [comment]
I guess I'm gonna close this issue, since the repository was updated.

I have one more request - since you're taking over development, please remove the donation link from the readme or replace it with your own - I don't want somebody to get confused and send me money when trying to support you. If you'd like, I can make a separate issue for that.

**Comment by KubeRoot** [comment]
@Frenqy Hey, I wanted to give a reminder - I'd appreciate it if you removed the donation link or replaced it with your own. I never got many donations and thankfully haven't gotten any from this yet, but I don't want to risk receiving donations meant for you. Hope you can get around to doing that sometime!

**Comment by Frenqy** [comment]
so sorry for that. i have removed it

**Comment by KubeRoot** [comment]
Nothing to be sorry about, you didn't do anything wrong - thanks for taking the time to do that.

Funnily, you did mess up updating the mod slightly - you previously had version 1.3.0 uploaded, and now uploaded 1.2.1. It seems it's pulling the readme from the highest version number, so it's still displaying the donation link. Just wanted to let you know.
